title: zaskoh
url: https://zaskoh.github.io
author: zaskoh
email: me@zaskoh.com
show_excerpts: false


description: >- # this means to ignore newlines until "baseurl:"
  I am a senior software engineer with over 5 years of experience, focusing on backend development and e-commerce. 
  I am interested in web3, blockchain, and smart contract security and looking to shift to web3 as a security researcher and solidity auditor in 2023.
  <a href="/about">more</a>

# paginate configuration
paginate: 5
paginate_path: "/blog/page:num/"

# tag configuration
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash configuration
dash:
  date_format: "%b %-d, %Y"
  animation_speed: 50
  avatar_source: local
  avatar_path: /assets/zaskoh.jpeg

  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/0xzaskoh
      icon: twitter-square
      color: blue
    - url: https://github.com/zaskoh
      icon: github-square
      color: purple
  
  # wether the author box should be displayed or not
  show_author: true


  # Build settings
theme: jekyll-dash

plugins:
  - liquid-md5
  - jekyll/tagging